server:
  port: 8443

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_vue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: tangjing666
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    learning: debug
